org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
loader_version=0.16.14
fabric_version=0.116.6+1.21.1

mod_id=emotecraft_fix_animate_texture
mod_name=Emotecraft Fix Animate Texture
mod_license=All Rights Reserved
mod_version=1.4.0
mod_group_id=emotecraft_fix_animate_texture
mod_authors=Catman0221
mod_description=Prevents Emotecraft emotes from conflicting with EMF player animations.
